name: cat_facts
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  get_it: ^7.6.4
  equatable: ^2.0.5
  pausable_timer: ^2.0.0+1
  bloc_concurrency: ^0.2.2
  flutter_staggered_animations: ^1.1.1
  hive: ^2.2.3
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  appwrite: ^11.0.0
  internet_connection_checker: ^1.0.0+1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
 
  fonts:
    - family: sfpt-regular
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
    - family: sfpt-medium
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
    - family: sfpt-bold
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
